### ISSUE TITLE
Explanation about the components in the basic.yml (for solution builder module)

### ISSUE THREAD

**Issue by SejeongPark8354** [nk53/auto_cgui#4]
I am very grateful for your work that organized CHARMM-GUI for use based on code. It seems like it will be a great help in my research as well.

I have a question about the components you typed in the basic.yml for solution builder module. 
You mentioned about Solutions Tests in the README, but I can't find the material. 
Is there any available material for understanding the components in the yml? 

Thank you once again.

**Comment by nk53** [comment]
It is complicated enough that it deserves to have its own section in the README. I will write something up today and post it here. If you are willing, I would appreciate any suggestions for things to add to my description to make it clearer before I finalize it and add it to the README.

**Comment by SejeongPark8354** [comment]
Thank you for your fast response. 
I've roughly understood what elements are in various yml files you uploaded through comparing them with the CHARMM-GUI webpage. Thanks! 

Does adding a ligand mean including a ligand component in the complex when necessary? 

hmr means hydrogen mass repartitioning, and hcr stands for hetero chain residue, right? 
If it's right, in the case of hcr, I guess I just need to enter what each hetero chain is? 
I'm also curious about the exact differences between terms like charmm, ctop_upload, param, etc., in the hcr.

Should I view chains as the same as selecting SEGID in the Model/Chain Selection Options? 
I asked because I've been entering them based on SEGID like PROA, HETE, etc., but sometimes I get an index error. 

Besides entering labels, I understood that everything else proceeds as default. 
The materials you've shared are already helpful for understanding, but it would be great if you could confirm the above contents.

**Comment by nk53** [comment]
> I've roughly understood what elements are in various yml files you uploaded through comparing them with the CHARMM-GUI webpage.

That is good, but considering that I still have to explain the process to new maintainers of Auto CGUI, I think it would be beneficial for everyone (including me) if I just write the process down while I am still familiar with the code.

Regardless, I'll answer your questions below.

> Does adding a ligand mean including a ligand component in the complex when necessary?

Yes. In case it is not obvious, you should store any files you want to upload to CHARMM-GUI in `files/` and use the `base` setting to specify where in `files/` any referenced pdb file can be found (default for PDB Reader and Solution Builder is probably `[files/]pdb/basic`).

> hmr means hydrogen mass repartitioning, and hcr stands for hetero chain residue, right?

Yes.

> in the case of hcr, I guess I just need to enter what each hetero chain is?

That depends on whether the ligand residue already exists in the CHARMM36m FF. If it does, then the entry for your ligand can be:
```yaml
hcr:
  - PDB_LIG_RESNAME CHARMMFF_LIG_RESNAME
```

This will choose the ligand's "rename to ____" option. In the example 5JY6 with CSML search (in `test_cases/pdb/csml.yml`), both uploaded and CHARMM residue names are NAD, so it's `- NAD NAD`

>  I'm also curious about the exact differences between terms like charmm, ctop_upload, param, etc., in the hcr.

Most of the time, the value of a setting comes directly from the related form element's HTML. If you are using Safari/Chrome/Firefox and have developer tools enabled, you can right-click the option you want to use, choose "inspect", and look for the HTML "value" attribute in the highlighted text in the inspector panel.

The CSML options however seem to be one of the cases that are somewhat different. Here's what I can see in the relevant Python code (`pdb_reader.py:PDBBrowserProcess.set_csml()`):
1. `charmm`: selects CGenFF and leaves other settings at the ligand's defaults (afaik, CGenFF is already the default, so I don't think this option does anything).
2. `antc`: selects Antechamber and leaves everything else default
3. `charmm_mol`: selects CGenFF with the "MOL2 file upload" option. The MOL2 file is expected to be located in the directory (relative to `files/`) specified by the `ligand` option (`files/ligands/basic` in all our examples), and named according to the input resname with `.mol2` file extension (e.g., NAD would be `NAD.mol2`).
4. `charmm_sdf`: like `charmm_mol`, but with SDF upload option and `.sdf` file extension.
5. `antc_mol` and `antc_sdf`: see `charmm_mol` and `charmm_sdf`.
6. `param`: opens the CSML Search window, waits for it to finish searching, and chooses "parameterize with PDB coordinates". It should be noted that this option does not appear if CSML finds a direct match in the CHARMM FF.
7. `ctop_upload`: seen in the `186l_modified` example, in which the "Upload CHARMM top & par" option is selected and `186l_modified.rtf` and `.prm` files are uploaded. This is inconsistent with the other ligand options and IDK why the this module's developer chose to use the PDB name as the base instead of the ligand name; perhaps he failed to consider the possibility of multiple ligands. However, that case can probably be handled within the current scheme by comining all top/par info into one RTF/PRM pair, uploading that pair for one of the ligands, and choosing the "rename to" option for all other ligands, using the residue names defined in the RTF/PRM files.

> Should I view chains as the same as selecting SEGID in the Model/Chain Selection Options?

Yes.

> I asked because I've been entering them based on SEGID like PROA, HETE, etc., but sometimes I get an index error.

Strange. Can you give an example of this happening?

**Comment by SejeongPark8354** [comment]
Thank you for your kind explanation. I understood everything you explained. thank you

I made the yml like below. 

```
- label: 8AZX_test
  pdb: 8azx.pdb
  ligand: ligands/basic
  chains:
    - PROA
    - HETE
  hcr:
    - OFU charmm
  input: gromacs
  hmr: true
```

and when I run the run_test.py, I got the error like below. 
```
Appending to existing logfile: results.log
starting solution
SolutionBrowserProcess-1 starting 8AZX_test
SolutionBrowserProcess-1 waiting for any text in: ['Manipulate PDB', 'CHARMM was terminated abnormally.', 'Error:']
SolutionBrowserProcess-1 Job ID: 9880245777
SolutionBrowserProcess-1 waiting for any text in: ['Manipulate PDB', 'CHARMM was terminated abnormally.', 'Fatal error:', 'Error:']
['PROA', 'HETE']
Traceback (most recent call last):
  File "/home/sejeong/anaconda3/envs/Pocket2Mol/lib/python3.8/site-packages/splinter/element_list.py", line 40, in __getitem__
    return self._container[index]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sejeong/codes/auto_cgui/cgui_browser_process.py", line 557, in run_full
    self.eval(prestep)
  File "/home/sejeong/codes/auto_cgui/cgui_browser_process.py", line 202, in eval
    return eval(expr)
  File "<string>", line 1, in <module>
  File "/home/sejeong/codes/auto_cgui/pdb_reader.py", line 651, in chain_select
    click_btn.click()
  File "/home/sejeong/anaconda3/envs/Pocket2Mol/lib/python3.8/site-packages/splinter/element_list.py", line 78, in __getattr__
    return getattr(self.first, name)
  File "/home/sejeong/anaconda3/envs/Pocket2Mol/lib/python3.8/site-packages/splinter/element_list.py", line 56, in first
    return self[0]
  File "/home/sejeong/anaconda3/envs/Pocket2Mol/lib/python3.8/site-packages/splinter/element_list.py", line 42, in __getitem__
    raise ElementDoesNotExist(
splinter.exceptions.ElementDoesNotExist: no elements could be found with name "chains[HETE][checked]"

downloading https://charmm-gui.org/?doc=input/download&jobid=9880245777 to charmm-gui-9880245777.tgz
Exception encountered for job (9880245777)
Traceback (most recent call last):
  File "/home/sejeong/anaconda3/envs/Pocket2Mol/lib/python3.8/site-packages/splinter/element_list.py", line 40, in __getitem__
    return self._container[index]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sejeong/codes/auto_cgui/cgui_browser_process.py", line 557, in run_full
    self.eval(prestep)
  File "/home/sejeong/codes/auto_cgui/cgui_browser_process.py", line 202, in eval
    return eval(expr)
  File "<string>", line 1, in <module>
  File "/home/sejeong/codes/auto_cgui/pdb_reader.py", line 651, in chain_select
    click_btn.click()
  File "/home/sejeong/anaconda3/envs/Pocket2Mol/lib/python3.8/site-packages/splinter/element_list.py", line 78, in __getattr__
    return getattr(self.first, name)
  File "/home/sejeong/anaconda3/envs/Pocket2Mol/lib/python3.8/site-packages/splinter/element_list.py", line 56, in first
    return self[0]
  File "/home/sejeong/anaconda3/envs/Pocket2Mol/lib/python3.8/site-packages/splinter/element_list.py", line 42, in __getitem__
    raise ElementDoesNotExist(
splinter.exceptions.ElementDoesNotExist: no elements could be found with name "chains[HETE][checked]"
```

**Comment by SejeongPark8354** [comment]
I figured out the reason for the error. It seems to have occurred because the chain names in the pdb file I uploaded are different from the chain names in the file directly obtained from RCSB. I've resolved it. Thank you.

**Comment by nk53** [comment]
Glad you figured it out. I would have responded sooner, but I got sick right after you sent your previous message.
